### ISSUE TITLE
How does the error handling work?

### ISSUE THREAD

**Issue by ianwalter** [probot/actions-adapter#6]
I see that errors from `probot.receive` are being caught here:
https://github.com/probot/actions-adapter/blob/master/index.js#L23-L24
But does probot also log the error? If not, shouldn't the error be logged so that you can see the stack trace, for example? Or maybe it can be refactored to use async/await and just throw the error like in this example? https://github.com/actions/toolkit/blob/5feb835dff800f53c9f6d8989f0b503262aade87/docs/github-package.md#action-logic

**Comment by swinton** [comment]
Thanks, good point. 

The easiest change here is to modify the adapter to throw. Working on it in #7.
