### ISSUE TITLE
Upgrade to Probot v10

### ISSUE THREAD

**Issue by gr2m** [probot/actions-adapter#8]
Hello GitHub Actions friends,

we just released Probot v10 and I'd like to upgrade `@probot/serverless-lambda` for compatibility. Would any existing user/contributor would like to collaborate on that with me?

More importantly, I'd like to make this package obsolete with Probot v11. I'm not sure how it would look like, but making Probot play nicely with serverless environments is our priority for the next release. Please join the discussion at
https://github.com/probot/probot/issues/1286

**Comment by gr2m** [comment]
This one is actually so simple, I think I'll just give this a go myself

**Comment by gr2m** [comment]
done via #11

**Comment by jetersen** [comment]
plans to upgrade this to v11 or is there a simpler way as you mentioned you planned to make obsolete.
